org.gradle.parallel=true
org.gradle.configuration-cache=false
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=37867
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=37867

minecraft_version=1.21.11
loader_version=0.19.5
loom_version=1.17.20
fabric_api_version=0.141.6+1.21.11

mod_version=1.0.0
maven_group=com.donuttest
archives_base_name=Donut-AC-Test-Client-1.21.11
